Repository NiJeTi/CinemaKeeper, pull requests merged in 2021-01, with the labels that each got.

#21 [feature 🧨🧨🧨]: added lock limit parameter if ur friend is not online …
  src/CinemaKeeper.Service/Modules/LockModule.cs
Labels: enhancement

#26 Dropped code-style rule set
  src/.editorconfig
Labels: documentation

#27 Code-style complex validation
  .github/workflows/validate.yaml
  src/.config/dotnet-tools.json
  src/.editorconfig
  src/CinemaKeeper.Service/Adapters/DiscordBotConfigurationAdapter.cs
  src/CinemaKeeper.Service/Adapters/IAdapter.cs
  src/CinemaKeeper.Service/Configurations/DiscordBotConfiguration.cs
  src/CinemaKeeper.Service/Extensions/ServiceProviderExtensions.cs
  src/CinemaKeeper.Service/Modules/LockModule.cs
  src/CinemaKeeper.Service/Modules/UnlockModule.cs
  src/CinemaKeeper.Service/Program.cs
  src/CinemaKeeper.Service/Services/BotService.cs
  src/CinemaKeeper.Service/Services/DiscordLoggingService.cs
Labels: enhancement

#29 Updated build pipeline
  .github/workflows/build.yaml
Labels: bug

#31 Fixed .EDITORCONFIG
  src/.editorconfig
  src/CinemaKeeper.Service/Configurations/DiscordBotConfiguration.cs
  src/CinemaKeeper.Service/Exceptions/UserNotInVoiceChannelException.cs
  src/CinemaKeeper.Service/Helpers/CommandExceptionShield.cs
  src/CinemaKeeper.Service/Services/BotService.cs
Labels: enhancement

#36 Changed rmi to pull
  cd/deploy_service.sh
Labels: enhancement

#41 Rolling log files on file size limit reach
  src/CinemaKeeper.Service/CinemaKeeper.Service.csproj
  src/CinemaKeeper.Service/appsettings.Development.json
Labels: bug
